# Generated by Django 5.1.7 on 2025-03-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0004_remove_empleado_contraseniaempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='inicioContrato',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de contrato'),
        ),
    ]
